sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    password: root
    #    不配置就默认为0
    database: 10

  wechat:
    appid: wxb7637baa5d8ccb7c
    secret: 62b54594db94da9b29a30066960079c4